-- ============================================
-- FILE 1: Seed Departments (Oracle SQL)
-- 8 departments with location and phone info.
-- head_employee_id is set AFTER employees exist (in 02_seed_employees.sql).
-- NOTE: Department.department_id must use GENERATED BY DEFAULT AS IDENTITY
--       to allow explicit ID inserts.
-- After seeding, reset with: ALTER TABLE Department MODIFY (department_id GENERATED ALWAYS AS IDENTITY START WITH LIMIT VALUE);
-- ============================================

INSERT INTO Department (department_id, head_employee_id, name, location, phone) VALUES (1, NULL, 'Cardiology', 'Building A, Floor 1', '617-555-0101');
INSERT INTO Department (department_id, head_employee_id, name, location, phone) VALUES (2, NULL, 'Orthopedics', 'Building A, Floor 2', '617-555-0102');
INSERT INTO Department (department_id, head_employee_id, name, location, phone) VALUES (3, NULL, 'Neurology', 'Building B, Floor 1', '617-555-0103');
INSERT INTO Department (department_id, head_employee_id, name, location, phone) VALUES (4, NULL, 'Pediatrics', 'Building B, Floor 2', '617-555-0104');
INSERT INTO Department (department_id, head_employee_id, name, location, phone) VALUES (5, NULL, 'Oncology', 'Building C, Floor 1', '617-555-0105');
INSERT INTO Department (department_id, head_employee_id, name, location, phone) VALUES (6, NULL, 'General Surgery', 'Building C, Floor 2', '617-555-0106');
INSERT INTO Department (department_id, head_employee_id, name, location, phone) VALUES (7, NULL, 'Emergency Medicine', 'Building D, Floor 1', '617-555-0107');
INSERT INTO Department (department_id, head_employee_id, name, location, phone) VALUES (8, NULL, 'Internal Medicine', 'Building D, Floor 2', '617-555-0108');

BEGIN
    DBMS_OUTPUT.PUT_LINE('Departments seeded successfully.');
END;
/

COMMIT;
