-- ============================================
-- FILE 5: Seed Rooms and Beds (Oracle SQL)
-- 50 rooms total:
--   25 rooms with 2 beds each (General, Semi-Private)
--   25 rooms with 1 bed each (ICU, Private, Operation Theatre)
-- 75 beds total with varied types
-- A few beds with is_maintenance = 1
-- NOTE: Room.room_id, Bed.bed_id must use GENERATED BY DEFAULT AS IDENTITY to allow explicit ID inserts.
-- After seeding, reset with:
--   ALTER TABLE Room MODIFY (room_id GENERATED ALWAYS AS IDENTITY START WITH LIMIT VALUE);
--   ALTER TABLE Bed MODIFY (bed_id GENERATED ALWAYS AS IDENTITY START WITH LIMIT VALUE);
-- ============================================

-- ============================================
-- SECTION 1: Rooms (50)
-- ============================================

-- General rooms (2 beds each) - Rooms 1-15
INSERT INTO Room (room_id, department_id, room_number, room_type, floor_number, is_active) VALUES (1, 1, 'G-101', 'General', 1, 1);
INSERT INTO Room (room_id, department_id, room_number, room_type, floor_number, is_active) VALUES (2, 1, 'G-102', 'General', 1, 1);
INSERT INTO Room (room_id, department_id, room_number, room_type, floor_number, is_active) VALUES (3, 2, 'G-201', 'General', 2, 1);
INSERT INTO Room (room_id, department_id, room_number, room_type, floor_number, is_active) VALUES (4, 2, 'G-202', 'General', 2, 1);
INSERT INTO Room (room_id, department_id, room_number, room_type, floor_number, is_active) VALUES (5, 3, 'G-301', 'General', 1, 1);
INSERT INTO Room (room_id, department_id, room_number, room_type, floor_number, is_active) VALUES (6, 3, 'G-302', 'General', 1, 1);
INSERT INTO Room (room_id, department_id, room_number, room_type, floor_number, is_active) VALUES (7, 4, 'G-401', 'General', 2, 1);
INSERT INTO Room (room_id, department_id, room_number, room_type, floor_number, is_active) VALUES (8, 4, 'G-402', 'General', 2, 1);
INSERT INTO Room (room_id, department_id, room_number, room_type, floor_number, is_active) VALUES (9, 5, 'G-501', 'General', 1, 1);
INSERT INTO Room (room_id, department_id, room_number, room_type, floor_number, is_active) VALUES (10, 5, 'G-502', 'General', 1, 1);
INSERT INTO Room (room_id, department_id, room_number, room_type, floor_number, is_active) VALUES (11, 6, 'G-601', 'General', 2, 1);
INSERT INTO Room (room_id, department_id, room_number, room_type, floor_number, is_active) VALUES (12, 6, 'G-602', 'General', 2, 1);
INSERT INTO Room (room_id, department_id, room_number, room_type, floor_number, is_active) VALUES (13, 7, 'G-701', 'General', 1, 1);
INSERT INTO Room (room_id, department_id, room_number, room_type, floor_number, is_active) VALUES (14, 7, 'G-702', 'General', 1, 1);
INSERT INTO Room (room_id, department_id, room_number, room_type, floor_number, is_active) VALUES (15, 8, 'G-801', 'General', 2, 1);

-- Semi-Private rooms (2 beds each) - Rooms 16-25
INSERT INTO Room (room_id, department_id, room_number, room_type, floor_number, is_active) VALUES (16, 1, 'SP-101', 'Semi-Private', 1, 1);
INSERT INTO Room (room_id, department_id, room_number, room_type, floor_number, is_active) VALUES (17, 2, 'SP-201', 'Semi-Private', 2, 1);
INSERT INTO Room (room_id, department_id, room_number, room_type, floor_number, is_active) VALUES (18, 3, 'SP-301', 'Semi-Private', 1, 1);
INSERT INTO Room (room_id, department_id, room_number, room_type, floor_number, is_active) VALUES (19, 4, 'SP-401', 'Semi-Private', 2, 1);
INSERT INTO Room (room_id, department_id, room_number, room_type, floor_number, is_active) VALUES (20, 5, 'SP-501', 'Semi-Private', 1, 1);
INSERT INTO Room (room_id, department_id, room_number, room_type, floor_number, is_active) VALUES (21, 6, 'SP-601', 'Semi-Private', 2, 1);
INSERT INTO Room (room_id, department_id, room_number, room_type, floor_number, is_active) VALUES (22, 7, 'SP-701', 'Semi-Private', 1, 1);
INSERT INTO Room (room_id, department_id, room_number, room_type, floor_number, is_active) VALUES (23, 8, 'SP-801', 'Semi-Private', 2, 1);
INSERT INTO Room (room_id, department_id, room_number, room_type, floor_number, is_active) VALUES (24, 1, 'SP-102', 'Semi-Private', 1, 1);
INSERT INTO Room (room_id, department_id, room_number, room_type, floor_number, is_active) VALUES (25, 3, 'SP-302', 'Semi-Private', 1, 1);

-- ICU rooms (1 bed each) - Rooms 26-35
INSERT INTO Room (room_id, department_id, room_number, room_type, floor_number, is_active) VALUES (26, 1, 'ICU-101', 'ICU', 1, 1);
INSERT INTO Room (room_id, department_id, room_number, room_type, floor_number, is_active) VALUES (27, 1, 'ICU-102', 'ICU', 1, 1);
INSERT INTO Room (room_id, department_id, room_number, room_type, floor_number, is_active) VALUES (28, 3, 'ICU-301', 'ICU', 1, 1);
INSERT INTO Room (room_id, department_id, room_number, room_type, floor_number, is_active) VALUES (29, 3, 'ICU-302', 'ICU', 1, 1);
INSERT INTO Room (room_id, department_id, room_number, room_type, floor_number, is_active) VALUES (30, 7, 'ICU-701', 'ICU', 1, 1);
INSERT INTO Room (room_id, department_id, room_number, room_type, floor_number, is_active) VALUES (31, 7, 'ICU-702', 'ICU', 1, 1);
INSERT INTO Room (room_id, department_id, room_number, room_type, floor_number, is_active) VALUES (32, 7, 'ICU-703', 'ICU', 1, 1);
INSERT INTO Room (room_id, department_id, room_number, room_type, floor_number, is_active) VALUES (33, 8, 'ICU-801', 'ICU', 2, 1);
INSERT INTO Room (room_id, department_id, room_number, room_type, floor_number, is_active) VALUES (34, 5, 'ICU-501', 'ICU', 1, 1);
INSERT INTO Room (room_id, department_id, room_number, room_type, floor_number, is_active) VALUES (35, 6, 'ICU-601', 'ICU', 2, 1);

-- Private rooms (1 bed each) - Rooms 36-45
INSERT INTO Room (room_id, department_id, room_number, room_type, floor_number, is_active) VALUES (36, 1, 'PV-101', 'Private', 3, 1);
INSERT INTO Room (room_id, department_id, room_number, room_type, floor_number, is_active) VALUES (37, 2, 'PV-201', 'Private', 3, 1);
INSERT INTO Room (room_id, department_id, room_number, room_type, floor_number, is_active) VALUES (38, 3, 'PV-301', 'Private', 3, 1);
INSERT INTO Room (room_id, department_id, room_number, room_type, floor_number, is_active) VALUES (39, 4, 'PV-401', 'Private', 3, 1);
INSERT INTO Room (room_id, department_id, room_number, room_type, floor_number, is_active) VALUES (40, 5, 'PV-501', 'Private', 3, 1);
INSERT INTO Room (room_id, department_id, room_number, room_type, floor_number, is_active) VALUES (41, 6, 'PV-601', 'Private', 3, 1);
INSERT INTO Room (room_id, department_id, room_number, room_type, floor_number, is_active) VALUES (42, 7, 'PV-701', 'Private', 3, 1);
INSERT INTO Room (room_id, department_id, room_number, room_type, floor_number, is_active) VALUES (43, 8, 'PV-801', 'Private', 3, 1);
INSERT INTO Room (room_id, department_id, room_number, room_type, floor_number, is_active) VALUES (44, 1, 'PV-102', 'Private', 3, 1);
INSERT INTO Room (room_id, department_id, room_number, room_type, floor_number, is_active) VALUES (45, 2, 'PV-202', 'Private', 3, 1);

-- Operation Theatre rooms (1 bed each) - Rooms 46-50
INSERT INTO Room (room_id, department_id, room_number, room_type, floor_number, is_active) VALUES (46, 6, 'OT-101', 'Operation Theatre', 1, 1);
INSERT INTO Room (room_id, department_id, room_number, room_type, floor_number, is_active) VALUES (47, 6, 'OT-102', 'Operation Theatre', 1, 1);
INSERT INTO Room (room_id, department_id, room_number, room_type, floor_number, is_active) VALUES (48, 1, 'OT-201', 'Operation Theatre', 1, 1);
INSERT INTO Room (room_id, department_id, room_number, room_type, floor_number, is_active) VALUES (49, 3, 'OT-301', 'Operation Theatre', 1, 1);
INSERT INTO Room (room_id, department_id, room_number, room_type, floor_number, is_active) VALUES (50, 2, 'OT-401', 'Operation Theatre', 1, 1);

BEGIN
    DBMS_OUTPUT.PUT_LINE('Rooms seeded successfully (50 rooms).');
END;
/

-- ============================================
-- SECTION 2: Beds (75)
-- Rooms 1-25: 2 beds each = 50 beds
-- Rooms 26-50: 1 bed each = 25 beds
-- Total = 75 beds
-- ============================================

-- Room 1 (General) - 2 beds
INSERT INTO Bed (bed_id, room_id, bed_number, bed_type, is_maintenance) VALUES (1, 1, 'G-101-A', 'Standard', 0);
INSERT INTO Bed (bed_id, room_id, bed_number, bed_type, is_maintenance) VALUES (2, 1, 'G-101-B', 'Standard', 0);
-- Room 2 (General) - 2 beds
INSERT INTO Bed (bed_id, room_id, bed_number, bed_type, is_maintenance) VALUES (3, 2, 'G-102-A', 'Standard', 0);
INSERT INTO Bed (bed_id, room_id, bed_number, bed_type, is_maintenance) VALUES (4, 2, 'G-102-B', 'Electric', 0);
-- Room 3 (General) - 2 beds
INSERT INTO Bed (bed_id, room_id, bed_number, bed_type, is_maintenance) VALUES (5, 3, 'G-201-A', 'Standard', 0);
INSERT INTO Bed (bed_id, room_id, bed_number, bed_type, is_maintenance) VALUES (6, 3, 'G-201-B', 'Standard', 0);
-- Room 4 (General) - 2 beds
INSERT INTO Bed (bed_id, room_id, bed_number, bed_type, is_maintenance) VALUES (7, 4, 'G-202-A', 'Electric', 0);
INSERT INTO Bed (bed_id, room_id, bed_number, bed_type, is_maintenance) VALUES (8, 4, 'G-202-B', 'Standard', 0);
-- Room 5 (General) - 2 beds
INSERT INTO Bed (bed_id, room_id, bed_number, bed_type, is_maintenance) VALUES (9, 5, 'G-301-A', 'Standard', 0);
INSERT INTO Bed (bed_id, room_id, bed_number, bed_type, is_maintenance) VALUES (10, 5, 'G-301-B', 'Standard', 0);
-- Room 6 (General) - 2 beds
INSERT INTO Bed (bed_id, room_id, bed_number, bed_type, is_maintenance) VALUES (11, 6, 'G-302-A', 'Electric', 0);
INSERT INTO Bed (bed_id, room_id, bed_number, bed_type, is_maintenance) VALUES (12, 6, 'G-302-B', 'Standard', 0);
-- Room 7 (General) - 2 beds
INSERT INTO Bed (bed_id, room_id, bed_number, bed_type, is_maintenance) VALUES (13, 7, 'G-401-A', 'Standard', 0);
INSERT INTO Bed (bed_id, room_id, bed_number, bed_type, is_maintenance) VALUES (14, 7, 'G-401-B', 'Standard', 0);
-- Room 8 (General) - 2 beds
INSERT INTO Bed (bed_id, room_id, bed_number, bed_type, is_maintenance) VALUES (15, 8, 'G-402-A', 'Electric', 0);
INSERT INTO Bed (bed_id, room_id, bed_number, bed_type, is_maintenance) VALUES (16, 8, 'G-402-B', 'Standard', 0);
-- Room 9 (General) - 2 beds
INSERT INTO Bed (bed_id, room_id, bed_number, bed_type, is_maintenance) VALUES (17, 9, 'G-501-A', 'Standard', 0);
INSERT INTO Bed (bed_id, room_id, bed_number, bed_type, is_maintenance) VALUES (18, 9, 'G-501-B', 'Standard', 0);
-- Room 10 (General) - 2 beds
INSERT INTO Bed (bed_id, room_id, bed_number, bed_type, is_maintenance) VALUES (19, 10, 'G-502-A', 'Bariatric', 0);
INSERT INTO Bed (bed_id, room_id, bed_number, bed_type, is_maintenance) VALUES (20, 10, 'G-502-B', 'Standard', 0);
-- Room 11 (General) - 2 beds
INSERT INTO Bed (bed_id, room_id, bed_number, bed_type, is_maintenance) VALUES (21, 11, 'G-601-A', 'Standard', 0);
INSERT INTO Bed (bed_id, room_id, bed_number, bed_type, is_maintenance) VALUES (22, 11, 'G-601-B', 'Electric', 0);
-- Room 12 (General) - 2 beds
INSERT INTO Bed (bed_id, room_id, bed_number, bed_type, is_maintenance) VALUES (23, 12, 'G-602-A', 'Standard', 0);
INSERT INTO Bed (bed_id, room_id, bed_number, bed_type, is_maintenance) VALUES (24, 12, 'G-602-B', 'Standard', 0);
-- Room 13 (General) - 2 beds
INSERT INTO Bed (bed_id, room_id, bed_number, bed_type, is_maintenance) VALUES (25, 13, 'G-701-A', 'Standard', 0);
INSERT INTO Bed (bed_id, room_id, bed_number, bed_type, is_maintenance) VALUES (26, 13, 'G-701-B', 'Electric', 0);
-- Room 14 (General) - 2 beds
INSERT INTO Bed (bed_id, room_id, bed_number, bed_type, is_maintenance) VALUES (27, 14, 'G-702-A', 'Bariatric', 0);
INSERT INTO Bed (bed_id, room_id, bed_number, bed_type, is_maintenance) VALUES (28, 14, 'G-702-B', 'Standard', 0);
-- Room 15 (General) - 2 beds
INSERT INTO Bed (bed_id, room_id, bed_number, bed_type, is_maintenance) VALUES (29, 15, 'G-801-A', 'Standard', 0);
INSERT INTO Bed (bed_id, room_id, bed_number, bed_type, is_maintenance) VALUES (30, 15, 'G-801-B', 'Electric', 0);

-- Room 16-25 (Semi-Private) - 2 beds each
INSERT INTO Bed (bed_id, room_id, bed_number, bed_type, is_maintenance) VALUES (31, 16, 'SP-101-A', 'Electric', 0);
INSERT INTO Bed (bed_id, room_id, bed_number, bed_type, is_maintenance) VALUES (32, 16, 'SP-101-B', 'Electric', 0);
INSERT INTO Bed (bed_id, room_id, bed_number, bed_type, is_maintenance) VALUES (33, 17, 'SP-201-A', 'Standard', 0);
INSERT INTO Bed (bed_id, room_id, bed_number, bed_type, is_maintenance) VALUES (34, 17, 'SP-201-B', 'Electric', 0);
INSERT INTO Bed (bed_id, room_id, bed_number, bed_type, is_maintenance) VALUES (35, 18, 'SP-301-A', 'Standard', 0);
INSERT INTO Bed (bed_id, room_id, bed_number, bed_type, is_maintenance) VALUES (36, 18, 'SP-301-B', 'Standard', 0);
INSERT INTO Bed (bed_id, room_id, bed_number, bed_type, is_maintenance) VALUES (37, 19, 'SP-401-A', 'Electric', 0);
INSERT INTO Bed (bed_id, room_id, bed_number, bed_type, is_maintenance) VALUES (38, 19, 'SP-401-B', 'Standard', 0);
INSERT INTO Bed (bed_id, room_id, bed_number, bed_type, is_maintenance) VALUES (39, 20, 'SP-501-A', 'Bariatric', 0);
INSERT INTO Bed (bed_id, room_id, bed_number, bed_type, is_maintenance) VALUES (40, 20, 'SP-501-B', 'Standard', 0);
INSERT INTO Bed (bed_id, room_id, bed_number, bed_type, is_maintenance) VALUES (41, 21, 'SP-601-A', 'Electric', 0);
INSERT INTO Bed (bed_id, room_id, bed_number, bed_type, is_maintenance) VALUES (42, 21, 'SP-601-B', 'Standard', 0);
INSERT INTO Bed (bed_id, room_id, bed_number, bed_type, is_maintenance) VALUES (43, 22, 'SP-701-A', 'Standard', 0);
INSERT INTO Bed (bed_id, room_id, bed_number, bed_type, is_maintenance) VALUES (44, 22, 'SP-701-B', 'Electric', 0);
INSERT INTO Bed (bed_id, room_id, bed_number, bed_type, is_maintenance) VALUES (45, 23, 'SP-801-A', 'Standard', 0);
INSERT INTO Bed (bed_id, room_id, bed_number, bed_type, is_maintenance) VALUES (46, 23, 'SP-801-B', 'Standard', 0);
INSERT INTO Bed (bed_id, room_id, bed_number, bed_type, is_maintenance) VALUES (47, 24, 'SP-102-A', 'Electric', 0);
INSERT INTO Bed (bed_id, room_id, bed_number, bed_type, is_maintenance) VALUES (48, 24, 'SP-102-B', 'Standard', 0);
INSERT INTO Bed (bed_id, room_id, bed_number, bed_type, is_maintenance) VALUES (49, 25, 'SP-302-A', 'Standard', 1);  -- MAINTENANCE
INSERT INTO Bed (bed_id, room_id, bed_number, bed_type, is_maintenance) VALUES (50, 25, 'SP-302-B', 'Electric', 0);

-- Room 26-35 (ICU) - 1 bed each
INSERT INTO Bed (bed_id, room_id, bed_number, bed_type, is_maintenance) VALUES (51, 26, 'ICU-101-A', 'ICU', 0);
INSERT INTO Bed (bed_id, room_id, bed_number, bed_type, is_maintenance) VALUES (52, 27, 'ICU-102-A', 'ICU', 0);
INSERT INTO Bed (bed_id, room_id, bed_number, bed_type, is_maintenance) VALUES (53, 28, 'ICU-301-A', 'ICU', 0);
INSERT INTO Bed (bed_id, room_id, bed_number, bed_type, is_maintenance) VALUES (54, 29, 'ICU-302-A', 'ICU', 1);  -- MAINTENANCE
INSERT INTO Bed (bed_id, room_id, bed_number, bed_type, is_maintenance) VALUES (55, 30, 'ICU-701-A', 'ICU', 0);
INSERT INTO Bed (bed_id, room_id, bed_number, bed_type, is_maintenance) VALUES (56, 31, 'ICU-702-A', 'ICU', 0);
INSERT INTO Bed (bed_id, room_id, bed_number, bed_type, is_maintenance) VALUES (57, 32, 'ICU-703-A', 'ICU', 0);
INSERT INTO Bed (bed_id, room_id, bed_number, bed_type, is_maintenance) VALUES (58, 33, 'ICU-801-A', 'ICU', 0);
INSERT INTO Bed (bed_id, room_id, bed_number, bed_type, is_maintenance) VALUES (59, 34, 'ICU-501-A', 'ICU', 0);
INSERT INTO Bed (bed_id, room_id, bed_number, bed_type, is_maintenance) VALUES (60, 35, 'ICU-601-A', 'ICU', 0);

-- Room 36-45 (Private) - 1 bed each
INSERT INTO Bed (bed_id, room_id, bed_number, bed_type, is_maintenance) VALUES (61, 36, 'PV-101-A', 'Electric', 0);
INSERT INTO Bed (bed_id, room_id, bed_number, bed_type, is_maintenance) VALUES (62, 37, 'PV-201-A', 'Electric', 0);
INSERT INTO Bed (bed_id, room_id, bed_number, bed_type, is_maintenance) VALUES (63, 38, 'PV-301-A', 'Electric', 0);
INSERT INTO Bed (bed_id, room_id, bed_number, bed_type, is_maintenance) VALUES (64, 39, 'PV-401-A', 'Electric', 0);
INSERT INTO Bed (bed_id, room_id, bed_number, bed_type, is_maintenance) VALUES (65, 40, 'PV-501-A', 'Electric', 1);  -- MAINTENANCE
INSERT INTO Bed (bed_id, room_id, bed_number, bed_type, is_maintenance) VALUES (66, 41, 'PV-601-A', 'Electric', 0);
INSERT INTO Bed (bed_id, room_id, bed_number, bed_type, is_maintenance) VALUES (67, 42, 'PV-701-A', 'Electric', 0);
INSERT INTO Bed (bed_id, room_id, bed_number, bed_type, is_maintenance) VALUES (68, 43, 'PV-801-A', 'Electric', 0);
INSERT INTO Bed (bed_id, room_id, bed_number, bed_type, is_maintenance) VALUES (69, 44, 'PV-102-A', 'Bariatric', 0);
INSERT INTO Bed (bed_id, room_id, bed_number, bed_type, is_maintenance) VALUES (70, 45, 'PV-202-A', 'Electric', 0);

-- Room 46-50 (Operation Theatre) - 1 bed each
INSERT INTO Bed (bed_id, room_id, bed_number, bed_type, is_maintenance) VALUES (71, 46, 'OT-101-A', 'Standard', 0);
INSERT INTO Bed (bed_id, room_id, bed_number, bed_type, is_maintenance) VALUES (72, 47, 'OT-102-A', 'Standard', 0);
INSERT INTO Bed (bed_id, room_id, bed_number, bed_type, is_maintenance) VALUES (73, 48, 'OT-201-A', 'Standard', 0);
INSERT INTO Bed (bed_id, room_id, bed_number, bed_type, is_maintenance) VALUES (74, 49, 'OT-301-A', 'Standard', 1);  -- MAINTENANCE
INSERT INTO Bed (bed_id, room_id, bed_number, bed_type, is_maintenance) VALUES (75, 50, 'OT-401-A', 'Standard', 0);

BEGIN
    DBMS_OUTPUT.PUT_LINE('Beds seeded successfully (75 beds, 4 in maintenance).');
END;
/

COMMIT;
