-- ============================================
-- FILE 8: Seed Prescriptions (Oracle SQL) (35 total)
-- ~20 linked to appointment_id (completed appointments 1-10)
-- ~15 linked to admission_id (admissions 1-10)
-- Realistic medications, dosages, frequencies
-- NOTE: Prescription.prescription_id must use GENERATED BY DEFAULT AS IDENTITY to allow explicit ID inserts.
-- After seeding, reset with: ALTER TABLE Prescription MODIFY (prescription_id GENERATED ALWAYS AS IDENTITY START WITH LIMIT VALUE);
-- ============================================

-- ============================================
-- APPOINTMENT-LINKED prescriptions (20)
-- From completed appointments (IDs 1-10)
-- ============================================

-- Appointment 1: Patient 1, Dr. Chen - Chest pain
INSERT INTO Prescription (prescription_id, appointment_id, admission_id, medication_name, dosage, frequency, duration_days, instructions, prescribed_at) VALUES (1, 1, NULL, 'Aspirin', '81 mg', 'Once daily', 90, 'Take with food in the morning', DATE '2026-04-14');
INSERT INTO Prescription (prescription_id, appointment_id, admission_id, medication_name, dosage, frequency, duration_days, instructions, prescribed_at) VALUES (2, 1, NULL, 'Atorvastatin', '20 mg', 'Once daily', 90, 'Take at bedtime', DATE '2026-04-14');

-- Appointment 2: Patient 2, Dr. Patel - Heart palpitations
INSERT INTO Prescription (prescription_id, appointment_id, admission_id, medication_name, dosage, frequency, duration_days, instructions, prescribed_at) VALUES (3, 2, NULL, 'Metoprolol', '25 mg', 'Twice daily', 30, 'Do not skip doses; take with meals', DATE '2026-04-14');
INSERT INTO Prescription (prescription_id, appointment_id, admission_id, medication_name, dosage, frequency, duration_days, instructions, prescribed_at) VALUES (4, 2, NULL, 'Magnesium Oxide', '400 mg', 'Once daily', 30, 'Take with a full glass of water', DATE '2026-04-14');

-- Appointment 3: Patient 3, Dr. Johnson - Knee pain
INSERT INTO Prescription (prescription_id, appointment_id, admission_id, medication_name, dosage, frequency, duration_days, instructions, prescribed_at) VALUES (5, 3, NULL, 'Ibuprofen', '600 mg', 'Three times daily', 14, 'Take with food to avoid stomach upset', DATE '2026-04-14');
INSERT INTO Prescription (prescription_id, appointment_id, admission_id, medication_name, dosage, frequency, duration_days, instructions, prescribed_at) VALUES (6, 3, NULL, 'Cyclobenzaprine', '10 mg', 'Three times daily', 7, 'May cause drowsiness; avoid driving', DATE '2026-04-14');

-- Appointment 4: Patient 4, Dr. Kim - Recurring headaches
INSERT INTO Prescription (prescription_id, appointment_id, admission_id, medication_name, dosage, frequency, duration_days, instructions, prescribed_at) VALUES (7, 4, NULL, 'Sumatriptan', '50 mg', 'As needed', 30, 'Take at first sign of migraine; max 2/day', DATE '2026-04-14');
INSERT INTO Prescription (prescription_id, appointment_id, admission_id, medication_name, dosage, frequency, duration_days, instructions, prescribed_at) VALUES (8, 4, NULL, 'Topiramate', '25 mg', 'Twice daily', 60, 'Titrate up to 50mg over 4 weeks', DATE '2026-04-14');

-- Appointment 5: Patient 5, Dr. O'Brien - Child wellness
INSERT INTO Prescription (prescription_id, appointment_id, admission_id, medication_name, dosage, frequency, duration_days, instructions, prescribed_at) VALUES (9, 5, NULL, 'Vitamin D3', '1000 IU', 'Once daily', 90, 'Chewable tablet with food', DATE '2026-04-14');

-- Appointment 6: Patient 6, Dr. Nguyen - Chemo follow-up
INSERT INTO Prescription (prescription_id, appointment_id, admission_id, medication_name, dosage, frequency, duration_days, instructions, prescribed_at) VALUES (10, 6, NULL, 'Ondansetron', '8 mg', 'Three times daily', 5, 'Take 30 min before meals for nausea', DATE '2026-04-14');
INSERT INTO Prescription (prescription_id, appointment_id, admission_id, medication_name, dosage, frequency, duration_days, instructions, prescribed_at) VALUES (11, 6, NULL, 'Dexamethasone', '4 mg', 'Twice daily', 3, 'Taper as directed', DATE '2026-04-14');

-- Appointment 7: Patient 7, Dr. Wright - Pre-op
INSERT INTO Prescription (prescription_id, appointment_id, admission_id, medication_name, dosage, frequency, duration_days, instructions, prescribed_at) VALUES (12, 7, NULL, 'Pantoprazole', '40 mg', 'Once daily', 14, 'Take 30 min before breakfast', DATE '2026-04-14');

-- Appointment 8: Patient 8, Dr. Lee - Ankle sprain
INSERT INTO Prescription (prescription_id, appointment_id, admission_id, medication_name, dosage, frequency, duration_days, instructions, prescribed_at) VALUES (13, 8, NULL, 'Naproxen', '500 mg', 'Twice daily', 10, 'Take with food; avoid alcohol', DATE '2026-04-14');
INSERT INTO Prescription (prescription_id, appointment_id, admission_id, medication_name, dosage, frequency, duration_days, instructions, prescribed_at) VALUES (14, 8, NULL, 'Acetaminophen', '500 mg', 'Every 6 hours', 7, 'Do not exceed 4g per day', DATE '2026-04-14');

-- Appointment 9: Patient 9, Dr. Davis - Annual physical
INSERT INTO Prescription (prescription_id, appointment_id, admission_id, medication_name, dosage, frequency, duration_days, instructions, prescribed_at) VALUES (15, 9, NULL, 'Lisinopril', '10 mg', 'Once daily', 90, 'Monitor blood pressure regularly', DATE '2026-04-14');
INSERT INTO Prescription (prescription_id, appointment_id, admission_id, medication_name, dosage, frequency, duration_days, instructions, prescribed_at) VALUES (16, 9, NULL, 'Metformin', '500 mg', 'Twice daily', 90, 'Take with meals to reduce GI side effects', DATE '2026-04-14');
INSERT INTO Prescription (prescription_id, appointment_id, admission_id, medication_name, dosage, frequency, duration_days, instructions, prescribed_at) VALUES (17, 9, NULL, 'Amlodipine', '5 mg', 'Once daily', 90, 'Take at the same time each day', DATE '2026-04-14');

-- Appointment 10: Patient 10, Dr. Thompson - Respiratory
INSERT INTO Prescription (prescription_id, appointment_id, admission_id, medication_name, dosage, frequency, duration_days, instructions, prescribed_at) VALUES (18, 10, NULL, 'Montelukast', '10 mg', 'Once daily', 60, 'Take in the evening', DATE '2026-04-14');
INSERT INTO Prescription (prescription_id, appointment_id, admission_id, medication_name, dosage, frequency, duration_days, instructions, prescribed_at) VALUES (19, 10, NULL, 'Albuterol Inhaler', '2 puffs', 'Every 4-6 hours', 30, 'Use as rescue inhaler for acute symptoms', DATE '2026-04-14');
INSERT INTO Prescription (prescription_id, appointment_id, admission_id, medication_name, dosage, frequency, duration_days, instructions, prescribed_at) VALUES (20, 10, NULL, 'Fluticasone Inhaler', '2 puffs', 'Twice daily', 90, 'Rinse mouth after each use', DATE '2026-04-14');

-- ============================================
-- ADMISSION-LINKED prescriptions (15)
-- From admissions 1-10
-- ============================================

-- Admission 1: Patient 51, acute MI (ICU)
INSERT INTO Prescription (prescription_id, appointment_id, admission_id, medication_name, dosage, frequency, duration_days, instructions, prescribed_at) VALUES (21, NULL, 1, 'Heparin', '5000 units', 'Every 12 hours', 7, 'Subcutaneous injection; monitor aPTT', DATE '2026-04-12');
INSERT INTO Prescription (prescription_id, appointment_id, admission_id, medication_name, dosage, frequency, duration_days, instructions, prescribed_at) VALUES (22, NULL, 1, 'Clopidogrel', '75 mg', 'Once daily', 30, 'Take with or without food', DATE '2026-04-12');
INSERT INTO Prescription (prescription_id, appointment_id, admission_id, medication_name, dosage, frequency, duration_days, instructions, prescribed_at) VALUES (23, NULL, 1, 'Nitroglycerin', '0.4 mg', 'As needed', 30, 'Sublingual; max 3 doses in 15 min, then call 911', DATE '2026-04-12');

-- Admission 2: Patient 52, hip replacement prep
INSERT INTO Prescription (prescription_id, appointment_id, admission_id, medication_name, dosage, frequency, duration_days, instructions, prescribed_at) VALUES (24, NULL, 2, 'Enoxaparin', '40 mg', 'Once daily', 14, 'DVT prophylaxis; inject in abdomen', DATE '2026-04-13');
INSERT INTO Prescription (prescription_id, appointment_id, admission_id, medication_name, dosage, frequency, duration_days, instructions, prescribed_at) VALUES (25, NULL, 2, 'Oxycodone', '5 mg', 'Every 6 hours', 7, 'For post-operative pain; avoid with alcohol', DATE '2026-04-13');

-- Admission 3: Patient 53, ischemic stroke (ICU)
INSERT INTO Prescription (prescription_id, appointment_id, admission_id, medication_name, dosage, frequency, duration_days, instructions, prescribed_at) VALUES (26, NULL, 3, 'Alteplase (tPA)', '0.9 mg/kg', 'Single dose', 1, 'IV thrombolytic; administered in first 4.5 hours', DATE '2026-04-13');
INSERT INTO Prescription (prescription_id, appointment_id, admission_id, medication_name, dosage, frequency, duration_days, instructions, prescribed_at) VALUES (27, NULL, 3, 'Aspirin', '325 mg', 'Once daily', 30, 'Start 24 hours after tPA', DATE '2026-04-14');

-- Admission 4: Patient 178 (minor), asthma exacerbation
INSERT INTO Prescription (prescription_id, appointment_id, admission_id, medication_name, dosage, frequency, duration_days, instructions, prescribed_at) VALUES (28, NULL, 4, 'Prednisolone', '30 mg', 'Once daily', 5, 'Oral corticosteroid burst; take with food', DATE '2026-04-12');
INSERT INTO Prescription (prescription_id, appointment_id, admission_id, medication_name, dosage, frequency, duration_days, instructions, prescribed_at) VALUES (29, NULL, 4, 'Ipratropium Nebulizer', '0.5 mg', 'Every 6 hours', 3, 'Nebulized bronchodilator', DATE '2026-04-12');

-- Admission 5: Patient 55, chemotherapy
INSERT INTO Prescription (prescription_id, appointment_id, admission_id, medication_name, dosage, frequency, duration_days, instructions, prescribed_at) VALUES (30, NULL, 5, 'Rituximab', '375 mg/m2', 'Weekly', 1, 'IV infusion; premedicate with acetaminophen', DATE '2026-04-11');
INSERT INTO Prescription (prescription_id, appointment_id, admission_id, medication_name, dosage, frequency, duration_days, instructions, prescribed_at) VALUES (31, NULL, 5, 'Filgrastim', '5 mcg/kg', 'Once daily', 10, 'Subcutaneous; for neutropenia prophylaxis', DATE '2026-04-11');

-- Admission 7 (discharged): Patient 57, appendicitis
INSERT INTO Prescription (prescription_id, appointment_id, admission_id, medication_name, dosage, frequency, duration_days, instructions, prescribed_at) VALUES (32, NULL, 7, 'Amoxicillin-Clavulanate', '875 mg', 'Twice daily', 10, 'Complete full course; take with food', DATE '2026-04-08');

-- Admission 8 (discharged): Patient 58, unstable angina
INSERT INTO Prescription (prescription_id, appointment_id, admission_id, medication_name, dosage, frequency, duration_days, instructions, prescribed_at) VALUES (33, NULL, 8, 'Nitroglycerin Patch', '0.2 mg/hr', 'Apply once daily', 30, 'Remove for 12 hours at night to prevent tolerance', DATE '2026-04-09');
INSERT INTO Prescription (prescription_id, appointment_id, admission_id, medication_name, dosage, frequency, duration_days, instructions, prescribed_at) VALUES (34, NULL, 8, 'Metoprolol Succinate', '50 mg', 'Once daily', 90, 'Extended release; do not crush or chew', DATE '2026-04-09');

-- Admission 10 (discharged): Patient 60, pneumonia
INSERT INTO Prescription (prescription_id, appointment_id, admission_id, medication_name, dosage, frequency, duration_days, instructions, prescribed_at) VALUES (35, NULL, 10, 'Amoxicillin', '500 mg', 'Three times daily', 7, 'Take with plenty of water; complete full course', DATE '2026-04-12');

BEGIN
    DBMS_OUTPUT.PUT_LINE('Prescriptions seeded successfully (35 records: 20 appointment-linked, 15 admission-linked).');
END;
/

COMMIT;
