-- ============================================
-- FILE 9: Seed Payments (Oracle SQL)
--
-- REVAMP:
--   - The Billing table was dropped. Billing is now embedded on
--     Appointment / Admission (see 06_seed_appointments.sql and
--     07_seed_admissions.sql).
--   - Payment.bill_id was replaced with direct FKs:
--     appointment_id and admission_id (exactly one must be set).
--   - processed_by references Employee(employee_id); seed leaves
--     this NULL because the original seed did not wire payments
--     back to a specific staff member.
--
-- Total: 52 payments (former payments 48-50 pointed at orphan bills
-- that no longer exist in the fold-in model and have been dropped).
--
-- NOTE: Payment.payment_id uses GENERATED BY DEFAULT AS IDENTITY to
-- allow explicit ID inserts. After seeding, reset with:
--   ALTER TABLE Payment MODIFY (payment_id GENERATED ALWAYS AS IDENTITY START WITH LIMIT VALUE);
-- ============================================

-- ============================================
-- Payments for COMPLETED appointments (1-10)
-- ============================================
INSERT INTO Payment (payment_id, appointment_id, admission_id, processed_by, amount, payment_method, transaction_ref, status, payment_date) VALUES (1, 1, NULL, NULL, 70.00, 'Credit Card', 'TXN-CC-20260414-001', 'Completed', DATE '2026-04-14');
INSERT INTO Payment (payment_id, appointment_id, admission_id, processed_by, amount, payment_method, transaction_ref, status, payment_date) VALUES (2, 2, NULL, NULL, 82.50, 'Debit Card', 'TXN-DC-20260414-002', 'Completed', DATE '2026-04-14');
INSERT INTO Payment (payment_id, appointment_id, admission_id, processed_by, amount, payment_method, transaction_ref, status, payment_date) VALUES (3, 3, NULL, NULL, 450.00, 'Insurance', 'TXN-INS-20260415-003', 'Completed', DATE '2026-04-15');
INSERT INTO Payment (payment_id, appointment_id, admission_id, processed_by, amount, payment_method, transaction_ref, status, payment_date) VALUES (4, 4, NULL, NULL, 150.00, 'Credit Card', 'TXN-CC-20260414-004', 'Completed', DATE '2026-04-14');
INSERT INTO Payment (payment_id, appointment_id, admission_id, processed_by, amount, payment_method, transaction_ref, status, payment_date) VALUES (5, 4, NULL, NULL, 350.00, 'Insurance', 'TXN-INS-20260415-005', 'Completed', DATE '2026-04-15');
INSERT INTO Payment (payment_id, appointment_id, admission_id, processed_by, amount, payment_method, transaction_ref, status, payment_date) VALUES (6, 5, NULL, NULL, 40.00, 'Cash', 'TXN-CASH-20260414-006', 'Completed', DATE '2026-04-14');
INSERT INTO Payment (payment_id, appointment_id, admission_id, processed_by, amount, payment_method, transaction_ref, status, payment_date) VALUES (7, 5, NULL, NULL, 160.00, 'Insurance', 'TXN-INS-20260415-007', 'Completed', DATE '2026-04-15');
INSERT INTO Payment (payment_id, appointment_id, admission_id, processed_by, amount, payment_method, transaction_ref, status, payment_date) VALUES (8, 6, NULL, NULL, 100.00, 'Credit Card', 'TXN-CC-20260414-008', 'Completed', DATE '2026-04-14');
INSERT INTO Payment (payment_id, appointment_id, admission_id, processed_by, amount, payment_method, transaction_ref, status, payment_date) VALUES (9, 6, NULL, NULL, 640.00, 'Insurance', 'TXN-INS-20260416-009', 'Completed', DATE '2026-04-16');
INSERT INTO Payment (payment_id, appointment_id, admission_id, processed_by, amount, payment_method, transaction_ref, status, payment_date) VALUES (10, 7, NULL, NULL, 90.00, 'Bank Transfer', 'TXN-CHK-20260414-010', 'Completed', DATE '2026-04-14');
INSERT INTO Payment (payment_id, appointment_id, admission_id, processed_by, amount, payment_method, transaction_ref, status, payment_date) VALUES (11, 7, NULL, NULL, 210.00, 'Insurance', 'TXN-INS-20260415-011', 'Completed', DATE '2026-04-15');
INSERT INTO Payment (payment_id, appointment_id, admission_id, processed_by, amount, payment_method, transaction_ref, status, payment_date) VALUES (12, 8, NULL, NULL, 50.00, 'Debit Card', 'TXN-DC-20260414-012', 'Completed', DATE '2026-04-14');
INSERT INTO Payment (payment_id, appointment_id, admission_id, processed_by, amount, payment_method, transaction_ref, status, payment_date) VALUES (13, 8, NULL, NULL, 200.00, 'Insurance', 'TXN-INS-20260415-013', 'Completed', DATE '2026-04-15');
INSERT INTO Payment (payment_id, appointment_id, admission_id, processed_by, amount, payment_method, transaction_ref, status, payment_date) VALUES (14, 9, NULL, NULL, 150.00, 'Insurance', 'TXN-INS-20260415-014', 'Completed', DATE '2026-04-15');
INSERT INTO Payment (payment_id, appointment_id, admission_id, processed_by, amount, payment_method, transaction_ref, status, payment_date) VALUES (15, 10, NULL, NULL, 30.00, 'Cash', 'TXN-CASH-20260414-015', 'Completed', DATE '2026-04-14');
INSERT INTO Payment (payment_id, appointment_id, admission_id, processed_by, amount, payment_method, transaction_ref, status, payment_date) VALUES (16, 10, NULL, NULL, 122.50, 'Insurance', 'TXN-INS-20260416-016', 'Completed', DATE '2026-04-16');

-- ============================================
-- Payments for DISCHARGED admissions (7-10)
-- ============================================
INSERT INTO Payment (payment_id, appointment_id, admission_id, processed_by, amount, payment_method, transaction_ref, status, payment_date) VALUES (17, NULL, 7, NULL, 4200.00, 'Insurance', 'TXN-INS-20260412-017', 'Completed', DATE '2026-04-12');
INSERT INTO Payment (payment_id, appointment_id, admission_id, processed_by, amount, payment_method, transaction_ref, status, payment_date) VALUES (18, NULL, 8, NULL, 3040.00, 'Insurance', 'TXN-INS-20260413-018', 'Completed', DATE '2026-04-13');
INSERT INTO Payment (payment_id, appointment_id, admission_id, processed_by, amount, payment_method, transaction_ref, status, payment_date) VALUES (19, NULL, 8, NULL, 400.00, 'Credit Card', 'TXN-CC-20260413-019', 'Completed', DATE '2026-04-13');
INSERT INTO Payment (payment_id, appointment_id, admission_id, processed_by, amount, payment_method, transaction_ref, status, payment_date) VALUES (20, NULL, 9, NULL, 3840.00, 'Insurance', 'TXN-INS-20260414-020', 'Completed', DATE '2026-04-14');
INSERT INTO Payment (payment_id, appointment_id, admission_id, processed_by, amount, payment_method, transaction_ref, status, payment_date) VALUES (21, NULL, 9, NULL, 500.00, 'Credit Card', 'TXN-CC-20260414-021', 'Completed', DATE '2026-04-14');
INSERT INTO Payment (payment_id, appointment_id, admission_id, processed_by, amount, payment_method, transaction_ref, status, payment_date) VALUES (22, NULL, 9, NULL, 460.00, 'Debit Card', 'TXN-DC-20260414-022', 'Completed', DATE '2026-04-14');
INSERT INTO Payment (payment_id, appointment_id, admission_id, processed_by, amount, payment_method, transaction_ref, status, payment_date) VALUES (23, NULL, 10, NULL, 5000.00, 'Insurance', 'TXN-INS-20260413-023', 'Completed', DATE '2026-04-13');

-- ============================================
-- Payments for ACTIVE admissions (1-6)
-- ============================================
INSERT INTO Payment (payment_id, appointment_id, admission_id, processed_by, amount, payment_method, transaction_ref, status, payment_date) VALUES (24, NULL, 1, NULL, 500.00, 'Credit Card', 'TXN-CC-20260413-024', 'Completed', DATE '2026-04-13');
INSERT INTO Payment (payment_id, appointment_id, admission_id, processed_by, amount, payment_method, transaction_ref, status, payment_date) VALUES (25, NULL, 2, NULL, 200.00, 'Debit Card', 'TXN-DC-20260413-025', 'Completed', DATE '2026-04-13');
INSERT INTO Payment (payment_id, appointment_id, admission_id, processed_by, amount, payment_method, transaction_ref, status, payment_date) VALUES (26, NULL, 4, NULL, 2800.00, 'Insurance', 'TXN-INS-20260413-026', 'Completed', DATE '2026-04-13');
INSERT INTO Payment (payment_id, appointment_id, admission_id, processed_by, amount, payment_method, transaction_ref, status, payment_date) VALUES (27, NULL, 5, NULL, 500.00, 'Cash', 'TXN-CASH-20260412-027', 'Completed', DATE '2026-04-12');
INSERT INTO Payment (payment_id, appointment_id, admission_id, processed_by, amount, payment_method, transaction_ref, status, payment_date) VALUES (28, NULL, 5, NULL, 2450.00, 'Insurance', 'TXN-INS-20260413-028', 'Completed', DATE '2026-04-13');
INSERT INTO Payment (payment_id, appointment_id, admission_id, processed_by, amount, payment_method, transaction_ref, status, payment_date) VALUES (29, NULL, 6, NULL, 1760.00, 'Insurance', 'TXN-INS-20260414-029', 'Completed', DATE '2026-04-14');

-- ============================================
-- Co-pays against scheduled appointment bills (21-35)
-- ============================================
INSERT INTO Payment (payment_id, appointment_id, admission_id, processed_by, amount, payment_method, transaction_ref, status, payment_date) VALUES (30, 21, NULL, NULL, 100.00, 'Credit Card', 'TXN-CC-20260415-030', 'Completed', DATE '2026-04-15');
INSERT INTO Payment (payment_id, appointment_id, admission_id, processed_by, amount, payment_method, transaction_ref, status, payment_date) VALUES (31, 22, NULL, NULL, 50.00, 'Cash', 'TXN-CASH-20260415-031', 'Completed', DATE '2026-04-15');
INSERT INTO Payment (payment_id, appointment_id, admission_id, processed_by, amount, payment_method, transaction_ref, status, payment_date) VALUES (32, 25, NULL, NULL, 150.00, 'Debit Card', 'TXN-DC-20260415-032', 'Completed', DATE '2026-04-15');
INSERT INTO Payment (payment_id, appointment_id, admission_id, processed_by, amount, payment_method, transaction_ref, status, payment_date) VALUES (33, 26, NULL, NULL, 80.00, 'Credit Card', 'TXN-CC-20260415-033', 'Completed', DATE '2026-04-15');
INSERT INTO Payment (payment_id, appointment_id, admission_id, processed_by, amount, payment_method, transaction_ref, status, payment_date) VALUES (34, 27, NULL, NULL, 40.00, 'Cash', 'TXN-CASH-20260415-034', 'Completed', DATE '2026-04-15');
INSERT INTO Payment (payment_id, appointment_id, admission_id, processed_by, amount, payment_method, transaction_ref, status, payment_date) VALUES (35, 28, NULL, NULL, 60.00, 'Debit Card', 'TXN-DC-20260415-035', 'Completed', DATE '2026-04-15');
INSERT INTO Payment (payment_id, appointment_id, admission_id, processed_by, amount, payment_method, transaction_ref, status, payment_date) VALUES (36, 29, NULL, NULL, 35.00, 'Credit Card', 'TXN-CC-20260415-036', 'Completed', DATE '2026-04-15');
INSERT INTO Payment (payment_id, appointment_id, admission_id, processed_by, amount, payment_method, transaction_ref, status, payment_date) VALUES (37, 30, NULL, NULL, 100.00, 'Cash', 'TXN-CASH-20260415-037', 'Completed', DATE '2026-04-15');
INSERT INTO Payment (payment_id, appointment_id, admission_id, processed_by, amount, payment_method, transaction_ref, status, payment_date) VALUES (38, 31, NULL, NULL, 90.00, 'Credit Card', 'TXN-CC-20260416-038', 'Completed', DATE '2026-04-16');
INSERT INTO Payment (payment_id, appointment_id, admission_id, processed_by, amount, payment_method, transaction_ref, status, payment_date) VALUES (39, 32, NULL, NULL, 70.00, 'Debit Card', 'TXN-DC-20260416-039', 'Completed', DATE '2026-04-16');
INSERT INTO Payment (payment_id, appointment_id, admission_id, processed_by, amount, payment_method, transaction_ref, status, payment_date) VALUES (40, 34, NULL, NULL, 75.00, 'Cash', 'TXN-CASH-20260416-040', 'Completed', DATE '2026-04-16');
INSERT INTO Payment (payment_id, appointment_id, admission_id, processed_by, amount, payment_method, transaction_ref, status, payment_date) VALUES (41, 35, NULL, NULL, 120.00, 'Credit Card', 'TXN-CC-20260416-041', 'Completed', DATE '2026-04-16');

-- ============================================
-- Additional installment payments on admissions 1, 3
-- ============================================
INSERT INTO Payment (payment_id, appointment_id, admission_id, processed_by, amount, payment_method, transaction_ref, status, payment_date) VALUES (42, NULL, 1, NULL, 200.00, 'Cash', 'TXN-CASH-20260414-042', 'Completed', DATE '2026-04-14');
INSERT INTO Payment (payment_id, appointment_id, admission_id, processed_by, amount, payment_method, transaction_ref, status, payment_date) VALUES (43, NULL, 3, NULL, 3500.00, 'Insurance', 'TXN-INS-20260414-043', 'Completed', DATE '2026-04-14');
INSERT INTO Payment (payment_id, appointment_id, admission_id, processed_by, amount, payment_method, transaction_ref, status, payment_date) VALUES (44, NULL, 3, NULL, 500.00, 'Credit Card', 'TXN-CC-20260414-044', 'Completed', DATE '2026-04-14');
INSERT INTO Payment (payment_id, appointment_id, admission_id, processed_by, amount, payment_method, transaction_ref, status, payment_date) VALUES (45, NULL, 3, NULL, 500.00, 'Debit Card', 'TXN-DC-20260415-045', 'Completed', DATE '2026-04-15');

-- ============================================
-- Late payments on no-show bills (appointments 18, 19)
-- ============================================
INSERT INTO Payment (payment_id, appointment_id, admission_id, processed_by, amount, payment_method, transaction_ref, status, payment_date) VALUES (46, 18, NULL, NULL, 50.00, 'Cash', 'TXN-CASH-20260420-046', 'Completed', DATE '2026-04-20');
INSERT INTO Payment (payment_id, appointment_id, admission_id, processed_by, amount, payment_method, transaction_ref, status, payment_date) VALUES (47, 19, NULL, NULL, 100.00, 'Credit Card', 'TXN-CC-20260422-047', 'Completed', DATE '2026-04-22');

-- ============================================
-- Remaining insurance + installment payments on admissions 1, 2, 5, 6
-- ============================================
INSERT INTO Payment (payment_id, appointment_id, admission_id, processed_by, amount, payment_method, transaction_ref, status, payment_date) VALUES (51, NULL, 2, NULL, 200.00, 'Bank Transfer', 'TXN-WT-20260414-051', 'Completed', DATE '2026-04-14');
INSERT INTO Payment (payment_id, appointment_id, admission_id, processed_by, amount, payment_method, transaction_ref, status, payment_date) VALUES (52, NULL, 5, NULL, 250.00, 'Credit Card', 'TXN-CC-20260414-052', 'Completed', DATE '2026-04-14');
INSERT INTO Payment (payment_id, appointment_id, admission_id, processed_by, amount, payment_method, transaction_ref, status, payment_date) VALUES (53, NULL, 6, NULL, 200.00, 'Cash', 'TXN-CASH-20260415-053', 'Completed', DATE '2026-04-15');
INSERT INTO Payment (payment_id, appointment_id, admission_id, processed_by, amount, payment_method, transaction_ref, status, payment_date) VALUES (54, NULL, 1, NULL, 3600.00, 'Insurance', 'TXN-INS-20260415-054', 'Completed', DATE '2026-04-15');
INSERT INTO Payment (payment_id, appointment_id, admission_id, processed_by, amount, payment_method, transaction_ref, status, payment_date) VALUES (55, NULL, 2, NULL, 2560.00, 'Insurance', 'TXN-INS-20260415-055', 'Completed', DATE '2026-04-15');

BEGIN
    DBMS_OUTPUT.PUT_LINE('Payments seeded successfully (52 records across Appointment and Admission sources).');
END;
/

COMMIT;
